config/routes.rb
Interview::Application.routes.draw do
  resources :monkeys

  root :to => 'monkeys#index'

end

app/models/monkey.rb
class Monkey < ActiveRecord::Base
  attr_accessible :description, :length_of_tail, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  # GET /monkeys
  # GET /monkeys.json
  def index
    @monkeys = Monkey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @monkeys }
    end
  end

  # GET /monkeys/1
  # GET /monkeys/1.json
  def show
    @monkey = Monkey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @monkey }
    end
  end

  # GET /monkeys/new
  # GET /monkeys/new.json
  def new
    @monkey = Monkey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @monkey }
    end
  end

  # GET /monkeys/1/edit
  def edit
    @monkey = Monkey.find(params[:id])
  end

  # POST /monkeys
  # POST /monkeys.json
  def create
    @monkey = Monkey.new(params[:monkey])

    respond_to do |format|
      if @monkey.save
        format.html { redirect_to @monkey, notice: 'Monkey was successfully created.' }
        format.json { render json: @monkey, status: :created, location: @monkey }
      else
        format.html { render action: "new" }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /monkeys/1
  # PUT /monkeys/1.json
  def update
    @monkey = Monkey.find(params[:id])

    respond_to do |format|
      if @monkey.update_attributes(params[:monkey])
        format.html { redirect_to @monkey, notice: 'Monkey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monkeys/1
  # DELETE /monkeys/1.json
  def destroy
    @monkey = Monkey.find(params[:id])
    @monkey.destroy

    respond_to do |format|
      format.html { redirect_to monkeys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interview</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/monkeys/_form.html.erb
<%= form_for(@monkey) do |f| %>
  <% if @monkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monkey.errors.count, "error") %> prohibited this monkey from being saved:</h2>

      <ul>
      <% @monkey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :length_of_tail %><br />
    <%= f.number_field :length_of_tail %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monkeys/edit.html.erb
<h1>Editing monkey</h1>

<%= render 'form' %>

<%= link_to 'Show', @monkey %> |
<%= link_to 'Back', monkeys_path %>

app/views/monkeys/index.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        var tableData = $('td[data-length-of-tail]');
        var $evenRows = [];

        console.log(tableData);
        console.log("this is executing");

        tableData.each(function() {
            console.log("This is executing!")
            console.log($(this).data('length-of-tail'));
            if ($(this).data('length-of-tail') % 2 === 0) {
                $evenRows.push($(this).parent('tr'));
            }
        });
        $.each($evenRows, function () {
            $(this).hide();
        });
    });
</script>

<h1>Listing monkeys</h1>

<table>
  <tr>
    <th>Length of tail</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @monkeys.each do |monkey| %>
      <tr>
        <td data-length-of-tail=<%= monkey.length_of_tail %>><%= monkey.length_of_tail %></td>
        <td><%= monkey.name %></td>
        <td><%= monkey.description %></td>
        <td><%= link_to 'Show', monkey %></td>
        <td><%= link_to 'Edit', edit_monkey_path(monkey) %></td>
        <td><%= link_to 'Destroy', monkey, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Monkey', new_monkey_path %>

app/views/monkeys/new.html.erb
<h1>New monkey</h1>

<%= render 'form' %>

<%= link_to 'Back', monkeys_path %>

app/views/monkeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Length of tail:</b>
  <%= @monkey.length_of_tail %>
</p>

<p>
  <b>Name:</b>
  <%= @monkey.name %>
</p>

<p>
  <b>Description:</b>
  <%= @monkey.description %>
</p>


<%= link_to 'Edit', edit_monkey_path(@monkey) %> |
<%= link_to 'Back', monkeys_path %>